name: Go WASM Build & Release

on:
  push:
    tags: ["v*"] # triggers release job only
  workflow_dispatch: # allows manual run for build

permissions:
  contents: write

env:
  GO_VERSION: "1.24" # can override

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build WASM
        run: |
          mkdir -p out
          make release
          mv out/wasm/workhorse.wasm out/workhorse.wasm

          ls -lh out

      - name: Generate SHA256 checksum
        id: checksum
        run: |
          sha256sum out/workhorse.wasm | tee out/workhorse.wasm.sha256
          echo "hash=$(sha256sum out/workhorse.wasm | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-artifacts
          path: out/

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') # only on tag push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm-artifacts
          path: out/

      - name: List files
        run: ls -lh out

      - name: Create GitHub Release (Draft)
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/workhorse.wasm
            out/workhorse.wasm.sha256
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this release
            - Auto-generated release from GitHub Actions

            ## SHA256 Checksum
            ```
            ${{ steps.checksum.outputs.hash }}
            ```
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
