name: Go WASM Build & Release

on:
  push:
    tags: ["v*"] # Triggers when a version tag (e.g., v1.0.0) is pushed
  workflow_dispatch:

permissions:
  contents: write

env:
  GO_VERSION: "1.24" # change here if needed

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build WASM
        run: |
          mkdir -p dist
          GOOS=js GOARCH=wasm go build -o dist/workhorse.wasm ./cmd/workhorse
          ls -lh dist

      - name: Generate SHA256 checksum
        id: checksum
        run: |
          sha256sum dist/workhorse.wasm | tee dist/workhorse.wasm.sha256
          echo "hash=$(sha256sum dist/workhorse.wasm | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release (Draft)
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/workhorse.wasm
            dist/workhorse.wasm.sha256
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this release
            - Auto-generated release from GitHub Actions

            ## SHA256 Checksum
            ```
            ${{ steps.checksum.outputs.hash }}
            ```
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
